---
- name: Upgrade VIO server in v4 context
  vars:
    min_vio_version: 4.1.0.10 # Validate at least above
    save_file: vio_savefiles.txt # Local list of files that get copied to v4 install
#    image_name: vio_4_1_1_0_mksysb # Name of mksysb image
#    image_host: aix7_nim # NFS server hosting image
#    image_dir: /export/mksysb # NFS directory containing image
    image_mount: /mnt
    file_list: "{{ lookup('file', '{{ save_file }}') }}" # List of files contained in safe_file
    dest_file: /tmp/vio_confirmed_savefiles.txt # Name of file created on VIO that lists all files
  #   in the save file that actually exists. Files that
  #   don't exist, cause an error with viosupgrade, hence
  #   the check if they exist
  hosts: all
  gather_facts: false
  # collections:
  #   - ibm.power_aix
  #   - ibm.power_vios
  tasks:
    - name: Get current VIO version
      register: ioslevel
      ansible.builtin.command: /usr/ios/cli/ioscli ioslevel
      changed_when: ioslevel.rc != 0

    - name: Display current VIO version
      ansible.builtin.debug:
        msg: "The current version before the upgrade is {{ ioslevel.stdout }} "

    - name: Validate version is at least '{{ min_vio_version }}'
      when: ioslevel.stdout is version(min_vio_version, '<')
      ansible.builtin.fail:
        msg: "Fail, starting version is too old, must be at least {{ min_vio_version }} to use this playbook. Current version is {{ ioslevel.stdout }}"

    - name: Exit successfully if already at target version
      ansible.builtin.meta: end_host
      when: ioslevel.stdout is version(target_version, '>=')

    - name: Add NFS mount for image host '{{ image_host }}' and directory '{{ image_dir }}'
      ibm.power_aix.filesystem:
        nfs_server: "{{ image_host }}"
        device: "{{ image_dir }}"
        filesystem: "{{ image_mount }}"
        nfs_soft_mount: true
        state: present
        fs_type: nfs
        permissions: ro

    - name: NFS mount of '{{ image_dir }}' from '{{ image_host }}'
      ibm.power_aix.mount:
        mount_dir: "{{ image_mount }}"
        state: mount

    - name: Validate altinst_rootvg exists
      register: altinst_status
      ansible.builtin.stat:
        path: /dev/altinst_rootvg

    - name: Fail if altinst_rootvg does not exist
      ansible.builtin.fail:
        msg: "ERROR: /dev/altinst_rootvg not found. Unable to proceed with upgrade."
      when: not altinst_status.stat.exists

    - name: Get hdisk associated to altinst_rootvg
      ansible.builtin.shell:
        cmd: |
          set -o pipefail # <-- adding this will prevent surprises
          lspv |grep altinst_rootvg | awk '{ print $1 }'
      register: altinst_hdisk
      when: altinst_status.stat.exists
      changed_when: altinst_hdisk.rc != 0

    - name: Vary off the VG
      ibm.power_aix.lvg:
        vg_name: altinst_rootvg
        state: varyoff
      when: altinst_status.stat.exists

    - name: Export VG for '{{ altinst_hdisk.stdout }}'
      ansible.builtin.command: exportvg altinst_rootvg
      when: altinst_status.stat.exists
      register: exportvg
      changed_when: exportvg.rc != 0

    - name: Clear PV
      ansible.builtin.command: chpv -C {{ altinst_hdisk.stdout }}
      when: altinst_status.stat.exists
      register: chpv
      changed_when: chpv.rc != 0

    # Commit is not necessary, but figure it's not a bad idea
    - name: Commit all uncommitted updated
      ibm.power_vios.updateios:
        action: commit
      ignore_errors: true

    - name: Grab the stats of all the files in "{{ save_file }}"
      with_items:
        - "{{ file_list.split('\n') }}"
      register: newlist
      ansible.builtin.stat:
        path: "{{ item }}"

    - name: Delete any existing temporary save file - "{{ dest_file }}"
      ansible.builtin.file:
        path: "{{ dest_file }}"
        state: absent

    - name: Create "{{ dest_file }}"
      ansible.builtin.file:
        path: "{{ dest_file }}"
        state: touch
        mode: "0600"

    - name: Create a new list of files that only contain existing files
      with_items:
        - "{{ newlist.results }}"
      when:
        - item.stat.exists
      ansible.builtin.lineinfile:
        line: "{{ item.stat.path }}"
        insertafter: EOF
        dest: "{{ dest_file }}"

    # Just for good housekeeping, store a copy of the configuration on the localhost
    - name: Backup VIO configuration
      ibm.power_vios.viosbr:
        action: backup
        file: "tmp/upgradebackup.{{ inventory_hostname }}"

    - name: Copy VIO Configuration
      ansible.builtin.fetch:
        src: "tmp/upgradebackup.{{ inventory_hostname }}.tar.gz"
        dest: /tmp/pre4upgradebackup.{{ inventory_hostname }}/
        flat: true

 # Just a friendly reminder this will take a bit
    - name: Warning! Next step is the actual install, patience
      ansible.builtin.debug:
        msg: Please be patient during the mksysb restore

    - name: Upgrade VIO
      ibm.power_vios.viosupgrade:
        image_file: "{{ image_mount }}/{{ image_name }}"
        mksysb_install_disks: "{{ altinst_hdisk.stdout }}"
        filename: "{{ dest_file }}"
        preserve_devname: true
        wait_reboot: true
        timeout: 120
      register: viosupgrade_var

    - name: Show some debug information
      ansible.builtin.debug:
        msg:
          - IOS level before {{ viosupgrade_var.ioslevel.before }}
          - IOS level after {{ viosupgrade_var.ioslevel.after }}
          - viosupgrade msg {{ viosupgrade_var.msg }}
          - Old rootvg disk {{ viosupgrade_var.old_rootvg }}

    - name: NFS unmount of '{{ image_dir }}' from '{{ image_host }}'
      ibm.power_aix.mount:
        mount_dir: "{{ image_dir }}"
        mount_over_dir: "{{ image_mount }}"
        state: umount

    - name: Remove NFS mount for image host '{{ image_host }}' and directory '{{ image_dir }}'
      ibm.power_aix.filesystem:
        nfs_server: "{{ image_host }}"
        device: "{{ image_dir }}"
        filesystem: "{{ image_mount }}"
        nfs_soft_mount: true
        state: absent

    - name: Get new VIO version
      ansible.builtin.command: /usr/ios/cli/ioscli ioslevel
      register: ioslevel
      changed_when: ioslevel.rc != 0

    - name: Display new VIO version
      ansible.builtin.debug:
        msg: "The current version after the upgrade is {{ ioslevel.stdout }} "
